### PR TITLE
Create osic-deployment

### PR DESCRIPTION
**Pull request by asettle**
Converted bare_metal_provisioning.md to .rst

### CODE REVIEW

**Comment by asettle** [comment]
@robb-romans - initial patch converting to RST. From here, we'll move the files into separate sections to work on a little easier. End goal to reflect the conventions here: http://docs.openstack.org/contributor-guide/writing-docs.html 
@raddaoui - are you okay with these changes? :)

**Comment by robb-romans** [comment]
Hi @asettle I have a couple of small fixes to push, but I get:
Pushing to git@github.com:asettle/ref-impl.git
ERROR: Permission to asettle/ref-impl.git denied to robb-romans.

**Comment by robb-romans** [comment]
Here's the change:

```
Add .rst file name extenstion; fix build error

1 file changed, 3 insertions(+), 3 deletions(-)
documents/{osic-deployment => osic-deployment.rst} | 6 +++---

**renamed    documents/osic-deployment -> documents/osic-deployment.rst**
@@ -153,9 +153,9 @@ following commands fail and you lose network connectivity:
 ::

     ifdown p1p1; ifup br-pxe
-    
-    Install LXC and Configure LXC Container
-~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+
+Install LXC and configure the LXC container
+~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 Install the necessary LXC package:

```

**Comment by mrhillsman** [comment]
You both should be able to merge this. If not let me know.

**Comment by asettle** [comment]
I will have to close this PR as Ala's changes from the previous night were not included. Another update to come :) Thanks @mrhillsman

**Pull request closed without merging**
